-- Load the GoSales customer dataset into Db2 for in-database ML.
--
-- ORGANIZE BY ROW is deliberate: the IDAX analytic stored procedures require
-- row-organized tables. This database defaults to ROW (DFT_TABLE_ORG), but
-- stating it keeps the script correct on a column-organized database too --
-- IBM ships a col_to_row_organize() helper precisely because this bites people.

CONNECT TO DB2AI;

DROP TABLE IF EXISTS GOSALES;
DROP TABLE IF EXISTS GOSALES_TRAIN;
DROP TABLE IF EXISTS GOSALES_TEST;
DROP TABLE IF EXISTS GOSALES_TRAIN_SUM1000;
DROP TABLE IF EXISTS GOSALES_TRAIN_SUM1000_CHAR;
DROP TABLE IF EXISTS GOSALES_TRAIN_SUM1000_NUM;
DROP TABLE IF EXISTS GOSALES_TEST_PREDICTIONS;

CREATE TABLE GOSALES (
    ID INTEGER NOT NULL,
    GENDER VARCHAR(3),
    AGE INTEGER,
    MARITAL_STATUS VARCHAR(30),
    PROFESSION VARCHAR(30),
    IS_TENT INTEGER,
    PRODUCT_LINE VARCHAR(30),
    PURCHASE_AMOUNT DECIMAL(30, 5),
    PRIMARY KEY (ID)
) ORGANIZE BY ROW;

IMPORT FROM 'gosales-data.csv' OF DEL SKIPCOUNT 1
    INSERT INTO GOSALES (ID, GENDER, AGE, MARITAL_STATUS, PROFESSION, IS_TENT, PRODUCT_LINE, PURCHASE_AMOUNT);

-- 60252 rows, with genuine gaps: ~2592 blank GENDER, ~2351 blank AGE,
-- ~770 blank MARITAL_STATUS. Those gaps are what IDAX.IMPUTE_DATA fixes later.
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM GOSALES;
SELECT COUNT(*) AS MISSING_GENDER FROM GOSALES WHERE GENDER IS NULL;
SELECT COUNT(*) AS MISSING_AGE    FROM GOSALES WHERE AGE IS NULL;

CONNECT RESET;
