CONNECT TO SAMPLE;

SELECT NAME, AGE, GENDER, CHOLESTEROL_LEVEL, BLOOD_PRESSURE, SMOKING_STATUS, 
VECTOR_DISTANCE((SELECT EMBEDDING FROM PATIENTS WHERE PATIENT_ID = 2), EMBEDDING, EUCLIDEAN) as DISTANCE
FROM PATIENTS
WHERE PATIENT_ID <> 2 
AND AGE BETWEEN 35 and 40 
ORDER BY DISTANCE ASC
FETCH FIRST 3 ROWS ONLY;

CONNECT RESET;