CONNECT TO sample;

DROP TABLE S1.SQ_SHOES;
DROP TABLE S1.SHOE_COLOR_SIZES;

CREATE TABLE S1.SQ_SHOES (
    SKU VARCHAR(8),
    PRODUCT_NAME VARCHAR(23),
    BRAND VARCHAR(9),
    CLASS VARCHAR(5),
    TYPE VARCHAR(7),
    MATERIAL VARCHAR(9),
    COLOR VARCHAR(5),
    WEATHER_RESISTANCE VARCHAR(10),
    ARCH_SUPPORT VARCHAR(4),
    SIZE FLOAT,
    PRICE FLOAT,
    RATING FLOAT,
    STORE_ID BIGINT,
    CITY VARCHAR(7),
    EMBEDDING VECTOR(1024, FLOAT32) -- Only if supported
);

CREATE TABLE S1.SHOE_COLOR_SIZES (
    SKU VARCHAR(8),
    COLOR VARCHAR(10),
    SIZE FLOAT
);

IMPORT FROM 'shoes-vectors.csv' OF DEL MODIFIED BY COLDEL, SKIPCOUNT 1 INSERT INTO S1.SQ_SHOES;
IMPORT FROM 'shoe_color_sizes.csv' OF DEL MODIFIED BY COLDEL, SKIPCOUNT 1 INSERT INTO S1.SHOE_COLOR_SIZES;

DISCONNECT sample;